name: lint
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  golint:
    runs-on: [self-hosted, pod]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: andstor/file-existence-action@v2
        id: check_files
        with:
          files: "go.mod"

      - name: setup go with docker
        run: |
          docker run --rm -v /usr/local:/sys_usr_local registry.smtx.io/sdn-base/golang:1.20 cp -r /usr/local/go /sys_usr_local/
          echo "PATH=${PATH}:/usr/local/go/bin" >> $GITHUB_ENV

      - name: setup golangci-lint from oci image
        run: |
          sudo docker run --rm -v /usr/local:/sys_usr_local registry.smtx.io/everoute/golangci-lint:1.62.2 cp -r /golangci-lint /sys_usr_local/bin/

      - uses: everoute/golangci-lint-action@v5
        with:
          install-mode: none
          skip-cache: true
          only-new-issues: true
        env:
          GOPROXY: http://goproxy.smartx.com|https://goproxy.cn|direct

  generate-check:
    runs-on: [self-hosted, pod]
    steps:
      - uses: actions/checkout@v3

      - name: make docker-generate
        run: sudo make docker-generate

      - name: check if code changes
        run: sudo sh -c "git add -A && git diff HEAD --exit-code"

      - name: show message if failed
        if: ${{ failure() }}
        run: echo "::error::Please run \"make generate\" or \"make docker-generate\" before commit."

  commitlint:
    runs-on: [self-hosted, pod]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v4
        with:
          configFile: .commitlintrc.json

  helmlint:
    runs-on: [self-hosted, pod]
    steps:
      - uses: actions/checkout@v3
      - uses: andstor/file-existence-action@v2
        id: check_files
        with:
          files: "./build/chart/Chart.yaml"
      - uses: azure/setup-helm@v3
        if: steps.check_files.outputs.files_exists == 'true'
        with:
          version: "v3.9.4"
      - if: steps.check_files.outputs.files_exists == 'true'
        run: helm lint ./build/chart
